// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3H4CyP8WrjaDNX6AS6qd3MKjp4aw5Uo',
    appId: '1:279407253737:web:a0e1f8c433f2829b10b878',
    messagingSenderId: '279407253737',
    projectId: 'chat-app-56f10',
    authDomain: 'chat-app-56f10.firebaseapp.com',
    storageBucket: 'chat-app-56f10.appspot.com',
    measurementId: 'G-42VHTE7DPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtUERT4yUuH0fmdTlIwMQAEp-z7EJgWQ',
    appId: '1:279407253737:android:94f27673aeffa6ad10b878',
    messagingSenderId: '279407253737',
    projectId: 'chat-app-56f10',
    storageBucket: 'chat-app-56f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPDg_1ZpjTfE5bQ45RSNKv42TN8hjtAkY',
    appId: '1:279407253737:ios:ae560331abf9f32710b878',
    messagingSenderId: '279407253737',
    projectId: 'chat-app-56f10',
    storageBucket: 'chat-app-56f10.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPDg_1ZpjTfE5bQ45RSNKv42TN8hjtAkY',
    appId: '1:279407253737:ios:f7abb56d9216047b10b878',
    messagingSenderId: '279407253737',
    projectId: 'chat-app-56f10',
    storageBucket: 'chat-app-56f10.appspot.com',
    iosBundleId: 'com.example.scholarChat.RunnerTests',
  );
}
